#!/usr/bin/env python3
"""Writes the two `.lproj` string tables from `strings.py`.

Run from the project root:

    python3 Tools/Localization/generate.py

Keys are the Chinese sentences the source uses, so `zh-Hans.lproj` is an
identity table and `en.lproj` carries the translations. Both files are written
whole every time — never edited by hand — which is what keeps them in step with
`strings.py`.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))

from keys import source_keys  # noqa: E402
from strings import EN  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
APP = ROOT / "BrewPhase"


def escape(text: str) -> str:
    """Escape only the double quote.

    Backslashes are left alone on purpose: a `\\n` in a key has to stay a
    two-character escape so the `.strings` parser turns it into a line break
    rather than a literal backslash.
    """
    return text.replace('"', '\\"')


def write_table(path: pathlib.Path, body: dict[str, str], header: str) -> None:
    lines = [header, ""]
    for key in sorted(body):
        lines.append(f'"{escape(key)}" = "{escape(body[key])}";')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}  ({len(body)} entries)")


def main() -> int:
    keys = source_keys()
    missing = sorted(set(keys) - set(EN))
    if missing:
        print(f"FAIL: {len(missing)} key(s) used in the source have no translation:")
        for key in missing:
            print(f'  "{key}"')
        return 1

    write_table(
        APP / "en.lproj" / "Localizable.strings",
        {key: EN[key] for key in keys},
        "/* Generated by Tools/Localization/generate.py — do not edit by hand. */",
    )
    write_table(
        APP / "zh-Hans.lproj" / "Localizable.strings",
        {key: key for key in keys},
        "/* Generated by Tools/Localization/generate.py — do not edit by hand. */",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
