"""The one place the app's copy is translated.

Keys are the Chinese source sentences — see `LanguageManager.swift` for why.
`EN` maps a key to its English text; `generate.py` writes both `.lproj` files
from this table, and `check.py` proves the table is complete and that no
translation has a different number of `%@` than its source.

Placeholders are always `%@` and always take a `String`. Never add or drop one,
and never reorder them: Foundation reads the arguments positionally, and a
mismatch is a crash rather than a bad label.
"""

EN: dict[str, str] = {
    # MARK: Plurals and counts
    "%@ · 剩余 %@": "%@ · %@ left",    "%@ 个文件 · %@": "%@ files · %@",
    "%@ 包": "%@ bags",
    "%@ 天": "%@ days",
    "%@ 条": "%@ entries",
    "%@ 条待送达": "%@ scheduled",
    "%@ 次": "%@ brews",
    "%@ 分": "%@ points",
    "%@ 星": "%@ stars",
    "约 %@ 天": "About %@ days",
    "约 %@ 次": "About %@ brews",
    "只剩 %@ 次的量": "Only about %@ brews left",
    "查看全部 %@ 条": "Show all %@",
    "清理 %@ 个无用的图片": "Clean up %@ unused images",
    "已清理 %@ 个文件": "Removed %@ files",
    "已自定义 %@ 项": "%@ customised",
    "保存后剩余 %@": "%@ left after saving",
    "烘焙 %@": "Roasted %@",
    "平均 %@/次": "averaging %@ a brew",
    "按默认 %@/次 估算": "estimated at %@ a brew",

    # MARK: Phase and its five words
    "太新": "Too fresh",
    "养豆": "Resting",
    "开始进入窗口": "Opening",
    "进入窗口": "Opening",
    "黄金风味窗口": "Peak window",
    "黄金窗口": "Peak",
    "风味衰退": "Declining",
    "衰退": "Declining",
    "开始衰退": "Declining",
    "建议优先消耗": "Use first",
    "建议优先饮用": "Use this one first",
    "正在养豆": "Resting",
    "风味开始打开": "the flavour is opening up",
    "现在喝": "drink now",
    "可以等": "No rush",
    "照常喝": "As usual",
    "建议优先": "Use first",
    "尽快喝完": "Finish it soon",

    # MARK: Today's pick
    "今天": "Today",
    "今天建议": "Today's pick",
    "早上好": "Good morning",
    "中午好": "Good midday",
    "下午好": "Good afternoon",
    "晚上好": "Good evening",
    "现在正处于风味窗口": "This one is in its window now",
    "风味正在打开": "The flavour is opening up",
    "风味已经开始衰退": "The flavour has started to decline",
    "还在养豆，风味还没打开": "Still resting — the flavour is not open yet",
    "已经喝完了": "This bag is finished",
    "还没有烘焙日期": "No roast date yet",
    "烘焙日期在未来": "The roast date is in the future",
    "窗口这两天就结束了": "The window closes in the next couple of days",
    "已过窗口但还剩不少": "Past its window with plenty left",
    "窗口比你的消耗速度更短": "The window is shorter than your pace",
    "上次这杯不太理想": "The last cup was not great",
    "还能冲": "brews left",
    "预计喝完": "Runs out",
    "不足一次": "Less than one brew",
    "已经见底": "almost gone",
    "预计还能喝 %@ 天": "about %@ days of coffee",
    "距离窗口结束约 %@ 天": "About %@ days left in the window",
    "窗口今天结束": "The window closes today",
    "已过窗口 %@ 天": "%@ days past the window",
    "已经进入窗口": "already in the window",
    "还有约 %@ 天进入窗口": "Opens in about %@ days",
    "填上烘焙日期就能看到阶段": "Add a roast date to see its phase",
    "填上烘焙日期，就能看到它现在处在哪个阶段": "Add the roast date and you will see which phase it is in",
    "烘焙日期在未来，请检查一下": "The roast date is in the future — worth a check",
    "排气期约 %@–%@ 天": "Rests for about %@–%@ days",
    "这包较晚才开封，封着的 %@ 天按半速计入，阶段相应顺延。": "Opened late — the %@ days it sat sealed count at half speed, so the phase is pushed back.",
    "这些是默认窗口，可以自己改": "These are the default windows — you can change them",
    "基于默认风味窗口估算": "estimated from the default window",

    # MARK: Reminders
    "提醒": "Reminders",
    "养豆完成": "Resting finished",
    "进入风味窗口": "Entered its window",
    "窗口过半": "Window halfway",
    "窗口即将结束": "Window closing",
    "排气期结束，风味开始打开时提醒": "When degassing ends and the flavour starts to open",
    "进入最佳风味窗口时提醒": "When it enters its peak window",
    "窗口走过一半时提醒": "When the window is half gone",
    "窗口结束前两天提醒": "Two days before the window closes",
    "这包可能喝不完它的窗口时提醒": "When a bag may not be finished inside its window",
    "%@ 养豆结束": "%@ has finished resting",
    "%@ 进入风味窗口": "%@ has entered its window",
    "%@ 的窗口过半了": "%@ is halfway through its window",
    "%@ 的窗口快结束了": "%@'s window is nearly over",
    "%@ 建议优先喝": "%@ — drink this one first",
    "%@ 的排气期基本结束，风味开始打开了。": "%@ has mostly finished degassing, and the flavour is starting to open up.",
    "%@ 现在进入最佳风味窗口，可以开始喝了。": "%@ is in its peak window now — a good time to start drinking it.",
    "%@ 的窗口已经过半，接下来的风味会慢慢变平。": "%@ is past the middle of its window; from here the flavour will slowly flatten.",
    "%@ 的窗口还剩两天，想喝到最好的状态就趁现在。": "%@ has two days left — now is the time if you want it at its best.",
    "%@ 的窗口比你的消耗速度更短，建议优先喝完。": "%@'s window is shorter than your pace, so it is worth finishing first.",
    "这包豆子": "This bean",
    "系统通知权限已关闭，提醒不会送达。可以在「设置 › 通知 › BrewPhase」里重新打开。": "Notifications are switched off for BrewPhase, so reminders will not arrive. You can turn them back on in Settings › Notifications › BrewPhase.",
    "还没有请求通知权限，添加第一包豆子时会问一次": "Notification permission has not been asked for yet — it comes up once when you add your first bean",
    "提醒会根据每包豆子的烘焙日期自动排好": "Reminders line themselves up from each bag's roast date",
    "提醒会根据烘焙日期一次排好，不需要 App 在后台运行。": "Reminders are scheduled in one go from the roast date; the app never needs to run in the background.",

    # MARK: The bean
    "豆仓": "Cellar",
    "豆子": "Beans",
    "豆子清单": "Bean list",
    "添加豆子": "Add bean",
    "编辑豆子": "Edit bean",
    "豆仓还是空的": "Your coffee shelf is empty",
    "添加第一包豆子，开始记录它从养豆到衰退的整个过程。": "Add your first bean and start tracking it from resting all the way to decline.",
    "豆名": "Name",
    "未命名": "Untitled",
    "谁烘的": "Who roasted it",
    "烘焙商": "Roaster",
    "产区": "Origin",
    "处理法": "Process",
    "烘焙度": "Roast level",
    "浅烘": "Light",
    "中烘": "Medium",
    "中深烘": "Medium-dark",
    "深烘": "Dark",
    "意式拼配": "Espresso blend",
    "烘焙日期": "Roast date",
    "购买日期": "Bought",
    "开封日期": "Opened",
    "已经开袋": "Already opened",
    "记录开封日期和剩余量": "Track the open date and how much is left",
    "总克数": "Total",
    "剩余克数": "Remaining",
    "剩余": "Left",
    "未填写": "Not set",
    "价格": "Price",
    "元": "CNY",
    "渠道": "Channel",
    "在哪里买的": "Where you bought it",
    "线下门店": "In person",
    "网店": "Online",
    "备注": "Notes",
    "想记的事情，比如冲煮建议": "Anything worth noting, e.g. what to change next time",
    "补充产区、处理法、价格": "Add origin, process and price",
    "烘焙与重量": "Roast and weight",
    "更多信息": "More details",
    "在喝": "Open",
    "已喝完": "Finished",
    "标记为已喝完": "Mark as finished",
    "库存": "Stock",
    "调整": "Adjust",
    "调整剩余量": "Adjust stock",
    "剩余量按总克数算": "Remaining is counted against the bag's total",
    "剩余量比总克数还多，保存时会按 %@ 调整总克数。": "There is more left than the bag holds; the total will be adjusted to %@ when you save.",
    "剩余量比总克数还多，已把总克数调到 %@": "There is more left than the bag holds, so the total was widened to %@",
    "剩余克数不能是负数": "The remaining amount cannot be negative",
    "总克数要大于 0": "The total weight has to be more than 0",
    "给它起个名字吧": "Give it a name",
    "烘焙日期还没选，风味阶段要靠它来算": "No roast date yet; the phase is worked out from it",
    "照片": "Photo",
    "加一张包装照片": "Add a photo of the bag",
    "拍照": "Camera",
    "相册": "Library",
    "换一张": "Replace",
    "移除": "Remove",
    "删除这包豆子": "Delete this bean",
    "删除这包豆子？": "Delete this bean?",
    "删除这包豆子后，它关联的 %@ 条冲煮记录和 %@ 条风味记录也会一起被删除，无法恢复。": "Deleting this bean also deletes its %@ brews and %@ tasting notes. This cannot be undone.",
    "删除": "Delete",
    "取消": "Cancel",
    "保存": "Save",
    "没能保存下来，请再试一次": "Could not save. Please try again",
    "这张图片没能保存下来，可以换一张试试": "That image could not be saved. Try another one",
    "比如 Ethiopia Guji": "e.g. Ethiopia Guji",
    "比如 埃塞俄比亚 · Guji": "e.g. Ethiopia · Guji",
    "水洗": "Washed",
    "半日晒": "Semi-washed",
    "厌氧日晒": "Anaerobic natural",
    "拼配": "Blend",
    "水洗 / 日晒 / 厌氧": "Washed / Natural / Anaerobic",

    # MARK: Flavour timeline
    "风味变化": "Flavour over time",
    "风味标签": "Flavour tags",
    "还没有标签": "No tags yet",
    "可以以后再补": "You can add these later",
    "自定义": "Custom",
    "自己写一个": "Write your own",
    "花香": "Floral",
    "水果": "Fruit",
    "甜感": "Sweetness",
    "茉莉": "Jasmine",
    "玫瑰": "Rose",
    "橙花": "Orange Blossom",
    "柑橘": "Mandarin",
    "葡萄": "Grape",
    "蓝莓": "Blueberry",
    "草莓": "Strawberry",
    "桃": "Peach",
    "蜂蜜": "Honey",
    "焦糖": "Caramel",
    "红糖": "Brown Sugar",
    "巧克力": "Chocolate",
    "来自冲煮记录": "from a brew",
    "风味记录": "Tasting note",
    "记一笔风味": "Add a tasting note",
    "还没有风味记录\\n冲一次，然后记下今天这杯怎么样。": "No tasting notes yet.\\nBrew this bean and note how today's cup tasted.",
    "这杯怎么样": "How was it",

    # MARK: Brewing
    "冲煮": "Brews",
    "冲煮记录": "Brews",
    "记一次冲煮": "Record a brew",
    "编辑冲煮": "Edit brew",
    "开始冲煮": "Brew now",
    "复制上次冲煮": "Copy last brew",
    "已填入上次的参数": "Filled in from your last brew",
    "复制": "Copy",
    "复制参数再来一次": "Brew again with the same recipe",
    "参数": "Recipe",
    "器具": "Method",
    "粉量": "Dose",
    "水量": "Water",
    "粉水比": "Ratio",
    "水温": "Water temp",
    "时间": "Time",
    "研磨度": "Grind",
    "磨豆机": "Grinder",
    "日期": "Date",
    "味觉细项": "Taste detail",
    "可留空": "Optional",
    "酸": "Acidity",
    "甜": "Sweet",
    "苦": "Bitter",
    "醇厚": "Body",
    "余韵": "Aftertaste",
    "一句话总结": "One-line summary",
    "· 这次用掉的比剩下的还多": "· that is more than you have left",
    "先填粉量吧，这样才能从库存里扣掉": "Fill in the dose first — it is what gets deducted from your stock",
    "水量还没填，粉水比会留空": "No water yet, so the ratio stays blank",
    "水温还没填": "The water temperature is not filled in yet",
    "冲煮时间还没填": "The brew time is not filled in yet",
    "删除这条记录": "Delete this brew",
    "还没有冲煮记录": "No brews yet",
    "还没有冲煮记录\\n冲一次，然后记下今天这杯怎么样。": "No brews yet.\\nBrew this bean and note how today's cup tasted.",
    "去豆仓挑一包，冲完记下参数和味道，这里就会长起来。": "Pick a bag from the cellar, brew it and note how it tasted — this is where it fills in.",
    "总次数": "Brews",
    "平均评分": "Average",
    "最常用": "Most used",
    "V60": "V60",
    "爱乐压": "AeroPress",
    "聪明杯": "Clever Dripper",
    "法压壶": "French press",
    "意式浓缩": "Espresso",
    "摩卡壶": "Moka pot",
    "冷萃": "Cold brew",
    "司令官 C40": "Comandante C40",
    "泰摩 栗子": "Timemore Chestnut",
    "22 格": "22 clicks",
    "比如 22 格": "e.g. 22 clicks",
    "比如 司令官 C40": "e.g. Comandante C40",
    "比如 甜感明显，下把可以再粗一点": "e.g. Sweet and clear; go a little coarser next time",
    "比如 甜感最明显，很干净": "e.g. Sweetest so far, very clean",

    # MARK: Settings
    "更多": "More",
    "默认冲煮参数": "Brew defaults",
    "新记录会从这里开始": "New brews start from these",
    "语言": "Language",
    "界面语言": "Language",
    "跟随系统": "Follow System",
    "立即生效": "Takes effect at once",
    "换语言不用重启，也不用改系统设置。选「跟随系统」就跟着手机走。": "No restart and no digging into system settings — pick “Follow System” and it tracks the phone.",
    "数据": "Data",
    "都在本机": "All local",
    "图片": "Photos",
    "导出": "Export",
    "导出 JSON": "Export JSON",
    "JSON 完整备份 · CSV 表格": "Full JSON backup · CSV tables",
    "完整备份": "Full backup",
    "表格": "Tables",
    "可以用 Excel 打开": "Opens in Excel",
    "包含豆子、冲煮、风味、提醒和窗口规则": "Beans, brews, tastings, reminders and window rules",
    "把记录带走": "Take your records with you",
    "导出的 JSON 可以完整还原你的记录。CSV 只包含豆子、冲煮和风味三张表，方便做统计。": "The JSON restores your records in full. The CSV holds three tables — beans, brews and tastings — for working with the numbers.",
    "导出的文件只保存在这台设备上，通过系统分享面板发给你自己。BrewPhase 不会上传任何东西。": "Exported files stay on this device and are handed to you through the system share sheet. BrewPhase uploads nothing.",
    "现在还没有记录。空数据也可以导出，出来的是一份结构完整、内容为空的文件。": "There are no records yet. An empty export is still fine — it comes out as a complete file with no records in it.",
    "正在准备文件…": "Preparing the files…",
    "导出时出了一点问题，请再试一次": "Something went wrong while exporting. Please try again",
    "没有需要清理的图片": "Nothing to clean up",
    "说明": "Notes",
    "风味": "Tastings",
    "规则": "Rules",
    "风味窗口": "Flavour windows",
    "风味窗口规则": "Window rules",
    "都是默认值": "All defaults",
    "排气开始": "Rest starts",
    "排气结束": "Rest ends",
    "窗口开始": "Window starts",
    "窗口结束": "Window ends",
    "衰退起点": "Decline starts",
    "已自定义": "Customised",
    "全部恢复默认": "Reset everything",
    "恢复默认": "Reset",
    "恢复默认窗口？": "Reset the windows?",
    "会把你改过的所有烘焙度都改回默认值。": "Every roast level you have edited goes back to its default.",
    "这些数字只是估算": "These numbers are estimates",
    "不同豆子、不同烘焙曲线都会不一样。下面是「%@」，改到符合你自己的经验就好。": "Every bean and every roast curve differs. The figures below are “%@”, so adjust them to match your own experience.",
    "这些数字只是「%@」，不是保质期，也不会说某包豆子过期了。": "These figures are only “%@”. They are not a use-by date, and the app will never call a bag expired.",
    "默认值：浅烘 7–28 天 · 中烘 5–21 天 · 中深烘 / 深烘 3–14 天 · 意式拼配 7–21 天。": "Defaults: Light 7–28 days · Medium 5–21 · Medium-dark / Dark 3–14 · Espresso blend 7–21.",
    "排气 %@–%@ · 窗口 %@–%@ · 衰退 %@": "Rest %@–%@ · Window %@–%@ · Decline %@",
    "排气 %@–%@ 天 · 窗口 %@–%@ 天 · %@": "Rest %@–%@ days · Window %@–%@ days · %@",
    "排气 %@–%@ 天 · 窗口第 %@–%@ 天 · 第 %@ 天开始衰退": "Rest %@–%@ days · Window days %@–%@ · Declining from day %@",
    "关于": "About",
    "没有账号，没有登录，没有服务器。": "No account, no sign-in, no server.",
    "飞行模式下也能完整使用。": "Everything works in aeroplane mode.",
    "所有数据随时可以导出带走。": "All your data can be exported at any time.",

    # MARK: Demo fixture — sample coffee, translated so the interface is never
    # half one language and half the other.
    "启程咖啡": "Qicheng Coffee",
    "有容": "Yourong",
    "朋友送的": "A gift from a friend",
    "埃塞俄比亚 · Guji": "Ethiopia · Guji",
    "哥伦比亚 · 慧兰": "Colombia · Huila",
    "肯尼亚 · Nyeri": "Kenya · Nyeri",
    "巴西 · Cerrado": "Brazil · Cerrado",
    "巴拿马 · Boquete": "Panama · Boquete",
    "手冲首选，V60 闷蒸 30 秒。": "First choice for pour-over; 30-second bloom on the V60.",
    "闻起来发酵感很足。": "Smells heavily fermented.",
    "先放着养一养。": "Leaving it to rest for now.",
    "深一点，做奶咖不错。": "A bit darker; good with milk.",
    "每天一杯奶咖的主力。": "The daily milk-drink workhorse.",
    "袋子上的烘焙日期磨掉了，等确认一下。": "The roast date on the bag has rubbed off — waiting to confirm it.",
    "刚开袋，酸质冲一点": "Just opened; the acidity is a bit sharp",
    "花香出来了，很干净": "The florals are showing, very clean",
    "目前最平衡的一杯": "The most balanced cup so far",
    "有点苦了": "A bit bitter",
    "入口有点闷": "A bit flat on entry",

    # MARK: Debug-only empty state, kept translated for screenshot parity
    "没有豆子可以展示": "Nothing to show yet",
    "简体中文": "简体中文",
}
